name: Melon Ticket VIP Automation
on:
  schedule:
    - cron: '*/2 * * * *'  # 每2分钟检查（开售前改为*/1）
  workflow_dispatch:       # 允许手动触发

jobs:
  reserve:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: VIP Ticket Check
        uses: mooyoul/melon-ticket-actions@v1.1.0
        with:
          product-id: "211541"
          schedule-id: "100001"
          seat-id: "10000"          # VIP석 seatGradeNo
          date: "2025-08-23"
          time: "18:00"
          price: "VIP석"            # 必须与seatGradeName完全一致
          count: "1"
          slack-incoming-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: 'VIP 티켓 감지! @team'
        env:
          MELON_USER_ID: ${{ secrets.MELON_USER_ID }}
          MELON_USER_PW: ${{ secrets.MELON_USER_PW }}
