name: Melon Ticket Automation
on:
  workflow_dispatch:
    inputs:
      product_id:
        description: 'Product ID (from URL)'
        required: true
        default: '211541'
      schedule_id:
        description: 'Schedule ID'
        required: true
        default: '100001'

jobs:
  reserve:
    runs-on: ubuntu-latest
    steps:
      - name: Check Tickets
        uses: mooyoul/melon-ticket-actions@v1.1.0
        with:
          product-id: ${{ github.event.inputs.product_id }}
          schedule-id: ${{ github.event.inputs.schedule_id }}
          seat-id: "10000"  # 必须通过API确认最新值
          slack-incoming-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL || '' }}
          message: 'Ticket check triggered'
